// Website adaptation of the canonical résumé and verified LinkedIn update, September 9, 2026.
// These are local-preview translations; public editorial approval is separate.
export function applyProfile(copy) {
  const translations = {
    en: {
      nav: ['Experience','Consulting','Selected projects','Insights','Contact'],
      home: ['Enterprise experience. Applied AI.','David Gargan — Principal AI Systems Architect. More than 25 years connecting enterprise information, governance, and hands-on engineering. Today: RAG, institutional memory, and multi-agent systems.','Explore my experience','Connect on LinkedIn'],
      intro: ['The information matters as much as the model.','My work connects a long career in enterprise content and information architecture with applied AI. I focus on how systems retrieve knowledge, preserve provenance, coordinate work, and keep people involved in consequential decisions.'],
      cards: [['expertise','01 / EXPERIENCE','Enterprise foundations.','OpenText ECM and xECM, records management, security, migrations, and information architecture.'],['development','02 / APPLIED AI','Systems with context.','Explore VALESKA, Commons, and DaveRouter: current work in knowledge, agent coordination, and governed execution.'],['consulting','03 / COLLABORATION','From architecture to delivery.','Technical consulting and principal-level architecture for organizations connecting AI to real information and workflows.']],
      experience: ['Experience behind the architecture','Enterprise knowledge, governed information, and applied AI grounded in delivery experience.',`<h2>David Gargan</h2><p>Founder &amp; Principal AI Systems Architect at Avanti AI Innovators since March 2024. My background spans more than 25 years of enterprise technology across government, defense, aerospace, energy, pharmaceutical, and commercial environments.</p><h2>Enterprise foundations</h2><p>My enterprise content work includes leading OpenText Content Server solution architecture at Stellar Services supporting the Texas Department of Public Safety, including information modeling, records management, integrations, workflows, and migration coordination.</p><p>As a consultant with OpenText, I delivered enterprise implementations, designed xECM records-management solutions, and led multi-day training seminars for employees and customers. Other engagements include TransCanada Energy, Sempra Energy, AliTek Consulting, Limited Brands, and BearingPoint.</p><p>Earlier work at NASA Dryden and Ames combined systems administration, application development, and research infrastructure. My U.S. Navy service included technical leadership and Portuguese translation and interpretation.</p><h2>Current technical focus</h2><p>RAG and semantic retrieval; PostgreSQL and pgvector; LLM evaluation; multi-agent coordination; provenance and governance; human review; Python, FastAPI, SQL, C#, REST APIs, Docker, Git, and Linux.</p><h2>Education &amp; languages</h2><p>B.A. in International Studies, University of South Florida. English (native), Portuguese (fluent; certified translator/interpreter), and Spanish (conversational).</p>`],
      projects: ['Selected AI projects','Current development work in enterprise knowledge, agent coordination, and applied AI.',`<h2>VALESKA — knowledge with provenance</h2><p>VALESKA is an enterprise knowledge and institutional-memory system. PostgreSQL provides the authoritative metadata and provenance layer, pgvector supports semantic retrieval, and a governed graph model represents entities, relationships, and cross-document assertions.</p><h2>Commons — coordination between agents</h2><p>Commons provides an API-centered coordination layer for independent agents and coding tools. Task and decision records, checkpoints, work ownership, and pre-action checks support coordination and human oversight.</p><h2>DaveRouter — governed execution</h2><p>DaveRouter is a policy-driven gateway that turns natural-language objectives into bounded work, selects execution resources, and reconciles results against coordination records and Git state.</p><h2>Applied AI beyond text</h2><p>Development work also includes local LLM training and evaluation workflows and computer-vision workflows for estate-sale inventory, with human review, labeling, and pricing operations.</p><h2>Creative AI: StoryLab</h2><p>The AI storytelling and video portfolio includes Transmissions from the Timeline and Cat &amp; Daniel: Collapse Protocol. StoryLab is a separate entity within AvantiComplex and has its own creative site.</p><p><a href="https://storylab.avanticomplex.com/">Explore StoryLab</a> · <a href="https://www.youtube.com/@TransmissionsfromtheTimeline">Watch the video portfolio</a></p><p>These summaries describe development work. They do not imply independently validated performance benchmarks or commercially available products.</p>`],
      contact: ['Let’s discuss your next system.','AI architecture and technical consulting for complex information and workflow challenges.','<h2>Connect with David</h2><p>Share the business problem, the systems involved, and what you need to accomplish using the form below. My experience combines enterprise information architecture with current applied AI engineering.</p>'],
      affiliation: 'An independent entity within AvantiComplex', email: 'Contact David'
    },
    es: {
      nav:['Experiencia','Consultoría','Proyectos destacados','Artículos','Contacto'],
      home:['Experiencia empresarial. IA aplicada.','David Gargan — Arquitecto principal de sistemas de IA. Más de 25 años conectando información empresarial, gobernanza e ingeniería. Hoy: RAG, memoria institucional y sistemas multiagente.','Conozca mi experiencia','Conectar en LinkedIn'],
      intro:['La información importa tanto como el modelo.','Mi trabajo conecta una larga trayectoria en contenidos y arquitectura de información empresarial con la IA aplicada. Me enfoco en recuperar conocimiento, conservar su procedencia, coordinar el trabajo y mantener la participación humana en decisiones importantes.'],
      cards:[['expertise','01 / EXPERIENCIA','Bases empresariales.','OpenText ECM y xECM, gestión documental, seguridad, migraciones y arquitectura de información.'],['development','02 / IA APLICADA','Sistemas con contexto.','VALESKA, Commons y DaveRouter: trabajo actual en conocimiento, coordinación de agentes y ejecución gobernada.'],['consulting','03 / COLABORACIÓN','De la arquitectura a la implementación.','Consultoría técnica y arquitectura para conectar la IA con información y procesos reales.']],
      experience:['Experiencia detrás de la arquitectura','Arquitectura empresarial, IA aplicada y la trayectoria detrás del trabajo.',`<h2>David Gargan</h2><p>Fundador y arquitecto principal de sistemas de IA de Avanti AI Innovators desde marzo de 2024. Más de 25 años de experiencia en tecnología empresarial en los sectores público, defensa, aeroespacial, energético, farmacéutico y comercial.</p><h2>Experiencia empresarial</h2><p>Mi experiencia incluye liderar en Stellar Services la arquitectura de soluciones OpenText Content Server para el Departamento de Seguridad Pública de Texas, incluyendo información, gestión documental, integraciones, procesos y coordinación de migraciones.</p><p>Como consultor técnico de OpenText, implementé soluciones empresariales, diseñé gestión documental con xECM y dirigí seminarios de formación de varios días para empleados y clientes. Otros trabajos incluyen TransCanada Energy, Sempra Energy, AliTek Consulting, Limited Brands y BearingPoint.</p><p>Mi experiencia anterior en NASA Dryden y Ames abarcó administración de sistemas, desarrollo e infraestructura de investigación. En la Marina de Estados Unidos ejercí liderazgo técnico y traducción e interpretación de portugués.</p><h2>Enfoque técnico actual</h2><p>RAG, recuperación semántica, PostgreSQL, pgvector, evaluación de LLM, coordinación multiagente, procedencia, gobernanza, revisión humana, Python, FastAPI, SQL, C#, API REST, Docker, Git y Linux.</p><h2>Formación e idiomas</h2><p>Licenciatura en Estudios Internacionales, University of South Florida. Inglés nativo, portugués fluido (traductor e intérprete certificado) y español conversacional.</p>`],
      projects:['Proyectos de IA destacados','Trabajo de desarrollo en conocimiento empresarial, coordinación de agentes e IA aplicada.',`<h2>VALESKA — conocimiento con procedencia</h2><p>VALESKA es un sistema de conocimiento y memoria institucional. PostgreSQL almacena metadatos y procedencia, pgvector permite recuperación semántica y un modelo de grafo gobernado representa entidades, relaciones y afirmaciones entre documentos.</p><h2>Commons — coordinación entre agentes</h2><p>Commons ofrece una capa de coordinación basada en API para agentes y herramientas de programación independientes. Incluye registros de tareas y decisiones, puntos de control, asignación del trabajo y comprobaciones previas a las acciones.</p><h2>DaveRouter — ejecución gobernada</h2><p>DaveRouter es una puerta de enlace basada en políticas que convierte objetivos en lenguaje natural en trabajo acotado, selecciona recursos de ejecución y contrasta los resultados con los registros de coordinación y Git.</p><h2>IA aplicada más allá del texto</h2><p>El trabajo de desarrollo también incluye entrenamiento y evaluación local de LLM y visión artificial para inventarios de ventas de bienes, con revisión humana, etiquetado y operaciones de precios.</p><h2>IA creativa: StoryLab</h2><p>El portafolio creativo incluye Transmissions from the Timeline y Cat &amp; Daniel: Collapse Protocol. StoryLab es una entidad independiente dentro de AvantiComplex, con su propio sitio creativo.</p><p><a href="https://storylab.avanticomplex.com/">Explorar StoryLab</a> · <a href="https://www.youtube.com/@TransmissionsfromtheTimeline">Ver el portafolio de video</a></p><p>Estos resúmenes describen trabajo de desarrollo. No implican resultados de rendimiento validados de forma independiente ni productos disponibles comercialmente.</p>`],
      contact:['Hablemos de su próximo sistema.','Arquitectura de IA y consultoría técnica para retos complejos de información y procesos.','<h2>Contacte con David</h2><p>Comparta el problema empresarial, los sistemas involucrados y el objetivo con el formulario a continuación. Mi experiencia combina arquitectura de información empresarial con ingeniería de IA aplicada.</p>'],
      affiliation:'Una entidad independiente dentro de AvantiComplex',email:'Contactar a David'
    },
    pt: {
      nav:['Experiência','Consultoria','Projetos em destaque','Artigos','Contato'],
      home:['Experiência empresarial. IA aplicada.','David Gargan — Arquiteto principal de sistemas de IA. Mais de 25 anos conectando informação empresarial, governança e engenharia. Hoje: RAG, memória institucional e sistemas multiagente.','Conheça minha experiência','Conectar no LinkedIn'],
      intro:['A informação importa tanto quanto o modelo.','Meu trabalho conecta uma longa trajetória em conteúdo e arquitetura da informação empresarial à IA aplicada. Meu foco é recuperar conhecimento, preservar sua proveniência, coordenar o trabalho e manter a participação humana em decisões importantes.'],
      cards:[['expertise','01 / EXPERIÊNCIA','Bases empresariais.','OpenText ECM e xECM, gestão documental, segurança, migrações e arquitetura da informação.'],['development','02 / IA APLICADA','Sistemas com contexto.','VALESKA, Commons e DaveRouter: trabalho atual em conhecimento, coordenação de agentes e execução governada.'],['consulting','03 / COLABORAÇÃO','Da arquitetura à implementação.','Consultoria técnica e arquitetura para conectar IA a informações e processos reais.']],
      experience:['Experiência por trás da arquitetura','Arquitetura empresarial, IA aplicada e a trajetória por trás do trabalho.',`<h2>David Gargan</h2><p>Fundador e arquiteto principal de sistemas de IA da Avanti AI Innovators desde março de 2024. Mais de 25 anos de experiência em tecnologia empresarial nos setores público, defesa, aeroespacial, energia, farmacêutico e comercial.</p><h2>Experiência empresarial</h2><p>Minha experiência inclui liderar na Stellar Services a arquitetura de soluções OpenText Content Server para o Departamento de Segurança Pública do Texas, incluindo informação, gestão documental, integrações, fluxos de trabalho e coordenação de migrações.</p><p>Como consultor técnico da OpenText, implementei soluções empresariais, projetei gestão documental com xECM e conduzi seminários de treinamento de vários dias para funcionários e clientes. Outros trabalhos incluem TransCanada Energy, Sempra Energy, AliTek Consulting, Limited Brands e BearingPoint.</p><p>Minha experiência anterior na NASA Dryden e Ames abrangeu administração de sistemas, desenvolvimento e infraestrutura de pesquisa. Na Marinha dos Estados Unidos, exerci liderança técnica e tradução e interpretação de português.</p><h2>Foco técnico atual</h2><p>RAG, recuperação semântica, PostgreSQL, pgvector, avaliação de LLM, coordenação multiagente, proveniência, governança, revisão humana, Python, FastAPI, SQL, C#, APIs REST, Docker, Git e Linux.</p><h2>Formação e idiomas</h2><p>Bacharelado em Estudos Internacionais pela University of South Florida. Inglês nativo, português fluente (tradutor e intérprete certificado) e espanhol conversacional.</p>`],
      projects:['Projetos de IA em destaque','Trabalho de desenvolvimento em conhecimento empresarial, coordenação de agentes e IA aplicada.',`<h2>VALESKA — conhecimento com proveniência</h2><p>VALESKA é um sistema de conhecimento e memória institucional. PostgreSQL armazena metadados e proveniência, pgvector oferece recuperação semântica e um modelo de grafo governado representa entidades, relações e afirmações entre documentos.</p><h2>Commons — coordenação entre agentes</h2><p>Commons oferece uma camada de coordenação baseada em API para agentes e ferramentas de programação independentes. Inclui registros de tarefas e decisões, pontos de controle, atribuição de trabalho e verificações antes de ações.</p><h2>DaveRouter — execução governada</h2><p>DaveRouter é um gateway baseado em políticas que converte objetivos em linguagem natural em trabalho delimitado, seleciona recursos de execução e confere resultados com registros de coordenação e Git.</p><h2>IA aplicada além do texto</h2><p>O trabalho de desenvolvimento também inclui treinamento e avaliação local de LLM e visão computacional para inventários de vendas de bens, com revisão humana, rotulagem e operações de preços.</p><h2>IA criativa: StoryLab</h2><p>O portfólio criativo inclui Transmissions from the Timeline e Cat &amp; Daniel: Collapse Protocol. StoryLab é uma entidade independente dentro do AvantiComplex, com seu próprio site criativo.</p><p><a href="https://storylab.avanticomplex.com/">Explorar StoryLab</a> · <a href="https://www.youtube.com/@TransmissionsfromtheTimeline">Ver o portfólio de vídeo</a></p><p>Estes resumos descrevem trabalho de desenvolvimento. Não implicam resultados de desempenho validados de forma independente nem produtos comercialmente disponíveis.</p>`],
      contact:['Vamos conversar sobre seu próximo sistema.','Arquitetura de IA e consultoria técnica para desafios complexos de informação e processos.','<h2>Converse com David</h2><p>Compartilhe o problema de negócio, os sistemas envolvidos e o objetivo usando o formulário abaixo. Minha experiência combina arquitetura da informação empresarial com engenharia de IA aplicada.</p>'],
      affiliation:'Uma entidade independente dentro do AvantiComplex',email:'Falar com David'
    }
  };
  for (const [locale,p] of Object.entries(translations)) {
    const c=copy[locale];
    Object.assign(c,{nav:p.nav,home:p.home,intro:p.intro,cards:p.cards,eyebrow:'DAVID GARGAN / AVANTI AI INNOVATORS'});
    c.pages.expertise=[c.pages.expertise[0],...p.experience];
    c.pages.development=[c.pages.development[0],...p.projects];
    c.pages.contact=[c.pages.contact[0],...p.contact];
    c.ui={...c.ui,affiliation:p.affiliation,email:p.email};
  }
}
