import {topics} from './topics.mjs';
import {applyConsulting} from './consulting.mjs';
import {applyProfile} from './profile.mjs';
// Initial migration copy. Review translations and positioning before public launch.
const copy = {
  en: {
    nav: ['Expertise','Consulting','AI development','Insights','Contact'],
    home: ['AI, connected to the way you work.','AI consulting, development, and integration for practical business challenges.','Explore our expertise','Let’s talk'],
    eyebrow: 'AVANTI AI INNOVATORS',
    intro: ['From possibility to practical application.','Start with the problem. Understand the systems and people involved. Build an approach that can be evaluated, integrated, and improved.'],
    cards: [
      ['consulting','01 / STRATEGY','Make a clear plan.','AI strategy, information management, and a practical roadmap for your organization.'],
      ['development','02 / DEVELOPMENT','Build around the task.','Custom applications and agentic workflows shaped around real business needs.'],
      ['expertise','03 / INTEGRATION','Connect the pieces.','Bring AI into existing systems through thoughtful architecture and API integration.']
    ],
    pages: {
      expertise: ['expertise','Expertise','AI strategy, development, integration, and ongoing support.','<h2>Start with your business</h2><p>We help organizations explore where AI fits, define a practical approach, and connect new capabilities to existing systems.</p><h2>Consulting</h2><p>AI strategy, information management, and solution design grounded in the problem you need to solve.</p><h2>AI development</h2><p>Custom applications, agentic workflows, and data-driven tools for business processes.</p><h2>Integration</h2><p>System architecture and API development to connect AI capabilities with existing tools and information.</p><h2>Support and maintenance</h2><p>Evaluate results, troubleshoot issues, and adapt the solution as requirements change.</p>'],
      consulting: ['consulting','A practical approach to AI.','Consulting that connects business priorities, information, and technology.','<h2>Understand the starting point</h2><p>Review your goals, workflows, data, and existing systems before selecting a solution.</p><h2>Shape the approach</h2><p>Define a manageable scope, evaluate options, and establish how success will be measured.</p><h2>Plan the integration</h2><p>Consider information management, system architecture, and the operational changes needed to support adoption.</p>'],
      development: ['ai-development','AI development with a purpose.','Applications and workflows designed around the work that needs to get done.','<h2>Define the task</h2><p>Identify the workflow, its inputs and outputs, and where human review is needed.</p><h2>Build and evaluate</h2><p>Develop a focused solution, test it against relevant examples, and inspect its limitations.</p><h2>Connect and improve</h2><p>Integrate with existing systems and refine the solution using observed results.</p>'],
      blog: ['blog','Ideas into practice.','Notes on AI, integration, and building useful systems.',''],
      contact: ['contact','Let’s discuss your project.','Tell us about the problem you are working on and what a useful outcome would look like.','<h2>Start a conversation</h2><p>Share your goals, current challenges, and any relevant timeline using the form below. Please avoid sending passwords, confidential records, or sensitive personal information.</p>'],
      privacy: ['privacy','Privacy','How this website handles information.','<h2>Browsing</h2><p>This version of the website does not use analytics scripts, advertising trackers, or browser cookies. Your language choice is part of the page address.</p><h2>Contact</h2><p>The contact form sends your name, email address, and message to Cloudflare, which relays it to us by email so we can respond to your inquiry. Before sending, Cloudflare Turnstile checks that the submission came from a person rather than automated software; this involves your browser exchanging a verification token with Cloudflare. We do not store your message in a database, and Cloudflare briefly rate-limits repeated submissions from the same network address to prevent abuse.</p><h2>Hosting</h2><p>Web servers and hosting providers may process connection information such as IP addresses and requested pages. Hosting arrangements and retention details must be reviewed before public launch.</p><h2>Questions</h2><p>Contact innovator@avanticomplex.com with privacy questions.</p>']
    },
    ui: { language:'Language', skip:'Skip to content', read:'Read article', empty:'Articles will appear here as they are published.', back:'All articles', email:'Contact us', related:'Explore further', more:'Explore', unavailable:'Not yet available in this language', next:'Next', previous:'Previous', page:'Page', footer:'AI consulting · Development · Integration', privacy:'Privacy', draft:'Local preview' }
  },
  es: {
    nav: ['Especialidades','Consultoría','Desarrollo de IA','Artículos','Contacto'],
    home: ['IA conectada con su forma de trabajar.','Consultoría, desarrollo e integración de IA para los retos prácticos de su empresa.','Conozca nuestras especialidades','Hablemos'],
    eyebrow:'AVANTI AI INNOVATORS',
    intro:['De la posibilidad a la aplicación práctica.','Comenzar por el problema. Comprender los sistemas y las personas involucradas. Crear un enfoque que se pueda evaluar, integrar y mejorar.'],
    cards:[
      ['consulting','01 / ESTRATEGIA','Definir un plan claro.','Estrategia de IA, gestión de la información y una hoja de ruta práctica para su organización.'],
      ['development','02 / DESARROLLO','Desarrollar según la tarea.','Aplicaciones y flujos de trabajo con agentes adaptados a necesidades empresariales reales.'],
      ['expertise','03 / INTEGRACIÓN','Conectar las piezas.','Incorporar la IA a los sistemas existentes mediante arquitectura e integración de API.']
    ],
    pages:{
      expertise:['especialidades','Especialidades','Estrategia, desarrollo, integración y soporte de IA.','<h2>Comenzar por su empresa</h2><p>Ayudamos a las organizaciones a explorar dónde encaja la IA, definir un enfoque práctico y conectar nuevas capacidades con los sistemas existentes.</p><h2>Consultoría</h2><p>Estrategia de IA, gestión de la información y diseño de soluciones centrados en el problema que necesita resolver.</p><h2>Desarrollo de IA</h2><p>Aplicaciones, flujos de trabajo con agentes y herramientas basadas en datos para procesos empresariales.</p><h2>Integración</h2><p>Arquitectura de sistemas y desarrollo de API para conectar la IA con las herramientas y la información existentes.</p><h2>Soporte y mantenimiento</h2><p>Evaluar resultados, resolver problemas y adaptar la solución cuando cambien los requisitos.</p>'],
      consulting:['consultoria','Un enfoque práctico de la IA.','Consultoría que conecta las prioridades empresariales, la información y la tecnología.','<h2>Comprender el punto de partida</h2><p>Revisar los objetivos, procesos, datos y sistemas existentes antes de elegir una solución.</p><h2>Definir el enfoque</h2><p>Establecer un alcance manejable, evaluar opciones y definir cómo medir el éxito.</p><h2>Planificar la integración</h2><p>Considerar la gestión de la información, la arquitectura y los cambios operativos necesarios para facilitar la adopción.</p>'],
      development:['desarrollo-ia','Desarrollo de IA con propósito.','Aplicaciones y procesos diseñados en torno al trabajo que se necesita realizar.','<h2>Definir la tarea</h2><p>Identificar el proceso, sus entradas y salidas, y los puntos que requieren revisión humana.</p><h2>Desarrollar y evaluar</h2><p>Crear una solución enfocada, probarla con ejemplos pertinentes y examinar sus limitaciones.</p><h2>Conectar y mejorar</h2><p>Integrar la solución con los sistemas existentes y perfeccionarla a partir de los resultados observados.</p>'],
      blog:['blog','De las ideas a la práctica.','Notas sobre IA, integración y desarrollo de sistemas útiles.',''],
      contact:['contacto','Hablemos de su proyecto.','Cuéntenos qué problema quiere resolver y cómo sería un resultado útil.','<h2>Iniciar una conversación</h2><p>Cuéntenos sus objetivos, retos actuales y plazos relevantes con el formulario a continuación. Evite incluir contraseñas, documentos confidenciales o información personal sensible.</p>'],
      privacy:['privacidad','Privacidad','Cómo trata la información este sitio web.','<h2>Navegación</h2><p>Esta versión no utiliza scripts de analítica, rastreadores publicitarios ni cookies del navegador. El idioma forma parte de la dirección de la página.</p><h2>Contacto</h2><p>El formulario de contacto envía su nombre, correo electrónico y mensaje a Cloudflare, que nos lo reenvía por correo para responder a su consulta. Antes de enviarlo, Cloudflare Turnstile comprueba que el envío proviene de una persona y no de software automatizado; esto implica que su navegador intercambia un token de verificación con Cloudflare. No almacenamos su mensaje en una base de datos, y Cloudflare limita brevemente los envíos repetidos desde la misma red para evitar abusos.</p><h2>Alojamiento</h2><p>Los servidores y proveedores de alojamiento pueden procesar información de conexión, como direcciones IP y páginas solicitadas. Los detalles del alojamiento y la conservación de datos deben revisarse antes del lanzamiento público.</p><h2>Preguntas</h2><p>Para consultas de privacidad, escriba a innovator@avanticomplex.com.</p>']
    },
    ui:{language:'Idioma',skip:'Ir al contenido',read:'Leer artículo',empty:'Los artículos aparecerán aquí a medida que se publiquen.',back:'Todos los artículos',email:'Contáctenos',related:'Más información',more:'Explorar',unavailable:'Aún no disponible en este idioma',next:'Siguiente',previous:'Anterior',page:'Página',footer:'Consultoría de IA · Desarrollo · Integración',privacy:'Privacidad',draft:'Vista previa local'}
  },
  pt:{
    nav:['Especialidades','Consultoria','Desenvolvimento de IA','Artigos','Contato'],
    home:['IA conectada à sua forma de trabalhar.','Consultoria, desenvolvimento e integração de IA para os desafios práticos da sua empresa.','Conheça nossas especialidades','Vamos conversar'],
    eyebrow:'AVANTI AI INNOVATORS',
    intro:['Da possibilidade à aplicação prática.','Começar pelo problema. Compreender os sistemas e as pessoas envolvidas. Construir uma abordagem que possa ser avaliada, integrada e aprimorada.'],
    cards:[
      ['consulting','01 / ESTRATÉGIA','Definir um plano claro.','Estratégia de IA, gestão da informação e um roteiro prático para sua organização.'],
      ['development','02 / DESENVOLVIMENTO','Desenvolver para a tarefa.','Aplicações e fluxos de trabalho com agentes voltados a necessidades reais de negócio.'],
      ['expertise','03 / INTEGRAÇÃO','Conectar as partes.','Incorporar a IA aos sistemas existentes por meio de arquitetura e integração de APIs.']
    ],
    pages:{
      expertise:['especialidades','Especialidades','Estratégia, desenvolvimento, integração e suporte de IA.','<h2>Começar pela sua empresa</h2><p>Ajudamos organizações a explorar onde a IA se encaixa, definir uma abordagem prática e conectar novas capacidades aos sistemas existentes.</p><h2>Consultoria</h2><p>Estratégia de IA, gestão da informação e desenho de soluções com foco no problema que você precisa resolver.</p><h2>Desenvolvimento de IA</h2><p>Aplicações, fluxos de trabalho com agentes e ferramentas baseadas em dados para processos de negócio.</p><h2>Integração</h2><p>Arquitetura de sistemas e desenvolvimento de APIs para conectar a IA às ferramentas e informações existentes.</p><h2>Suporte e manutenção</h2><p>Avaliar resultados, solucionar problemas e adaptar a solução conforme os requisitos mudam.</p>'],
      consulting:['consultoria','Uma abordagem prática para a IA.','Consultoria que conecta prioridades de negócio, informação e tecnologia.','<h2>Entender o ponto de partida</h2><p>Revisar objetivos, processos, dados e sistemas existentes antes de escolher uma solução.</p><h2>Definir a abordagem</h2><p>Estabelecer um escopo viável, avaliar opções e definir como medir o sucesso.</p><h2>Planejar a integração</h2><p>Considerar a gestão da informação, a arquitetura e as mudanças operacionais necessárias para apoiar a adoção.</p>'],
      development:['desenvolvimento-ia','Desenvolvimento de IA com propósito.','Aplicações e fluxos de trabalho projetados para o que precisa ser feito.','<h2>Definir a tarefa</h2><p>Identificar o processo, suas entradas e saídas, e os pontos que precisam de revisão humana.</p><h2>Desenvolver e avaliar</h2><p>Criar uma solução focada, testá-la com exemplos relevantes e examinar suas limitações.</p><h2>Conectar e melhorar</h2><p>Integrar aos sistemas existentes e aperfeiçoar a solução com base nos resultados observados.</p>'],
      blog:['blog','Das ideias à prática.','Notas sobre IA, integração e desenvolvimento de sistemas úteis.',''],
      contact:['contato','Vamos conversar sobre seu projeto.','Conte qual problema você está tentando resolver e como seria um resultado útil.','<h2>Iniciar uma conversa</h2><p>Conte seus objetivos, desafios atuais e prazos relevantes usando o formulário abaixo. Evite enviar senhas, documentos confidenciais ou informações pessoais sensíveis.</p>'],
      privacy:['privacidade','Privacidade','Como este site trata informações.','<h2>Navegação</h2><p>Esta versão não utiliza scripts de análise, rastreadores publicitários ou cookies do navegador. O idioma faz parte do endereço da página.</p><h2>Contato</h2><p>O formulário de contato envia seu nome, e-mail e mensagem para a Cloudflare, que os repassa para nós por e-mail para que possamos responder à sua consulta. Antes do envio, o Cloudflare Turnstile verifica se o envio veio de uma pessoa e não de software automatizado; isso envolve seu navegador trocando um token de verificação com a Cloudflare. Não armazenamos sua mensagem em um banco de dados, e a Cloudflare limita brevemente envios repetidos da mesma rede para evitar abusos.</p><h2>Hospedagem</h2><p>Servidores e provedores de hospedagem podem processar informações de conexão, como endereços IP e páginas solicitadas. Os detalhes de hospedagem e retenção devem ser revisados antes do lançamento público.</p><h2>Dúvidas</h2><p>Para questões de privacidade, escreva para innovator@avanticomplex.com.</p>']
    },
    ui:{language:'Idioma',skip:'Ir para o conteúdo',read:'Ler artigo',empty:'Os artigos aparecerão aqui à medida que forem publicados.',back:'Todos os artigos',email:'Fale conosco',related:'Saiba mais',more:'Explorar',unavailable:'Ainda não disponível neste idioma',next:'Próxima',previous:'Anterior',page:'Página',footer:'Consultoria de IA · Desenvolvimento · Integração',privacy:'Privacidade',draft:'Prévia local'}
  }
};
applyProfile(copy);
applyConsulting(copy);
export const seed = Object.entries(copy).flatMap(([locale,c]) => [
  {key:'home',kind:'page',locale,slug:'home',title:c.home[0],description:c.home[1],body:'',data:{eyebrow:c.eyebrow,primary:c.home[2],secondary:c.home[3],intro:c.intro,cards:c.cards}},
  {key:'shell',kind:'page',locale,slug:'shell',title:'Avanti AI Innovators',description:'',body:'',data:{nav:c.nav,ui:c.ui}},
  ...Object.entries(c.pages).map(([key,p])=>({key,kind:'page',locale,slug:p[0],title:p[1],description:p[2],body:p[3],data:key==='blog'?{topics:topics.map(t=>({id:t.id,title:t[locale][0],description:t[locale][1],image:t.image,secondaryImage:t.secondaryImage,motif:t.motif}))}:{}}))
]);
